In [6]:
import os
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import seaborn as sns

In [2]:
Data_test = pd.read_csv('/kaggle/input/clear-data/Clear_Data_test_kaggle (1).csv')
Data_test

,ID,PERIODO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_TIENELAVADORA,FAMI_TIENEAUTOMOVIL,ESTU_PRIVADO_LIBERTAD,ESTU_PAGOMATRICULAPROPIO,...,ESTU_PRGM_ACADEMICO_TEOLOGIA,ESTU_PRGM_ACADEMICO_TERAPIA CARDIORRESPIRATORIA,ESTU_PRGM_ACADEMICO_TERAPIA OCUPACIONAL,ESTU_PRGM_ACADEMICO_TERAPIA RESPIRATORIA,ESTU_PRGM_ACADEMICO_TERAPIAS PSICOSOCIALES,ESTU_PRGM_ACADEMICO_TRABAJO SOCIAL,ESTU_PRGM_ACADEMICO_TRADUCCION INGLES-FRANCES-ESPANOL,ESTU_PRGM_ACADEMICO_TURISMO,ESTU_PRGM_ACADEMICO_URBANISMO,ESTU_PRGM_ACADEMICO_ZOOTECNIA
0,721274,20195,4,1,0.0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,250531,20213,2,1,0.0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,585681,20195,0,3,0.0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,767608,20195,4,3,0.0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,112077,20183,2,2,0.0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296781,770258,20183,4,4,6.0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
296782,261058,20203,7,1,6.0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
296783,390818,20212,7,3,6.0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
296784,573310,20183,7,0,6.0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
296785,812332,20183,7,1,6.0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
Data_columns = Data_test.columns
Data_columns

Index(['ID', 'PERIODO', 'ESTU_VALORMATRICULAUNIVERSIDAD',
       'ESTU_HORASSEMANATRABAJA', 'FAMI_ESTRATOVIVIENDA', 'FAMI_TIENEINTERNET',
       'FAMI_TIENELAVADORA', 'FAMI_TIENEAUTOMOVIL', 'ESTU_PRIVADO_LIBERTAD',
       'ESTU_PAGOMATRICULAPROPIO',
       ...
       'ESTU_PRGM_ACADEMICO_TEOLOGIA',
       'ESTU_PRGM_ACADEMICO_TERAPIA CARDIORRESPIRATORIA',
       'ESTU_PRGM_ACADEMICO_TERAPIA OCUPACIONAL',
       'ESTU_PRGM_ACADEMICO_TERAPIA RESPIRATORIA',
       'ESTU_PRGM_ACADEMICO_TERAPIAS PSICOSOCIALES',
       'ESTU_PRGM_ACADEMICO_TRABAJO SOCIAL',
       'ESTU_PRGM_ACADEMICO_TRADUCCION INGLES-FRANCES-ESPANOL',
       'ESTU_PRGM_ACADEMICO_TURISMO', 'ESTU_PRGM_ACADEMICO_URBANISMO',
       'ESTU_PRGM_ACADEMICO_ZOOTECNIA'],
      dtype='object', length=785)

In [4]:
len(Data_columns)

785

In [7]:
df = pd.read_csv('/kaggle/input/clear-data/Clear_Data (3).csv')
df

,ID,PERIODO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_TIENELAVADORA,FAMI_TIENEAUTOMOVIL,ESTU_PRIVADO_LIBERTAD,ESTU_PAGOMATRICULAPROPIO,...,ESTU_PRGM_ACADEMICO_TERAPIA CARDIORRESPIRATORIA,ESTU_PRGM_ACADEMICO_TERAPIA OCUPACIONAL,ESTU_PRGM_ACADEMICO_TERAPIA RESPIRATORIA,ESTU_PRGM_ACADEMICO_TERAPIAS PSICOSOCIALES,ESTU_PRGM_ACADEMICO_TRABAJO SOCIAL,ESTU_PRGM_ACADEMICO_TRADUCCION INGLES-FRANCES-ESPANOL,ESTU_PRGM_ACADEMICO_TURISMO,ESTU_PRGM_ACADEMICO_URBANISMO,ESTU_PRGM_ACADEMICO_ZOOTECNIA,RENDIMIENTO_GLOBAL
0,547092,20195,3,4,0.0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,236193,20183,3,1,0.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,481044,20183,3,0,0.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,609421,20203,2,2,0.0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,89078,20183,2,4,0.0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
692495,783274,20195,7,0,6.0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,3
692496,310249,20183,7,4,6.0,1,1,1,0,1,...,0,0,0,0,0,0,0,0,0,3
692497,110623,20203,7,1,6.0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,2
692498,949271,20203,3,4,6.0,1,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
692499,44851,20203,4,2,6.0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Calcular el número de filas que representa el 5% del DataFrame
num_rows_5_percent = int(len(df) * 0.05)

# Extraer el 5% de los datos al azar
df = df.sample(n=num_rows_5_percent, random_state=42)

# Ahora df_5_percent contiene el 5% de los datos del DataFrame original

df

In [8]:
def split_fit_predict(estimator, X, y, train_pct):

    def split_data(X, y, pct):  
        
        # Dividir los datos en conjuntos de entrenamiento y prueba    

        return train_test_split(X, y, test_size=1-pct, random_state=42)

    def accuracy(y_true, y_pred):

        assert len(y_true)==len(y_pred), "X and y must have the same length"
        result = sum(y_true == y_pred)/len(y_pred)
        return result

    Xtr, Xts, ytr, yts = split_data(X, y, train_pct)

    print("Entrenando ...")
    #... fit the estimator ....
    estimator.fit(Xtr.drop(columns=['ID']),ytr)
    
    print("Test ...")

    #... obtain predictions ...
    preds_ts = estimator.predict(Xts.drop(columns=['ID']))
    
    print("OK")

    return Xts['ID'],yts, accuracy(yts, preds_ts)

In [9]:
X = df.iloc[:, :-1]
common_columns = X.columns.intersection(Data_test.columns)
X = X[common_columns]
X

,ID,PERIODO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_TIENELAVADORA,FAMI_TIENEAUTOMOVIL,ESTU_PRIVADO_LIBERTAD,ESTU_PAGOMATRICULAPROPIO,...,ESTU_PRGM_ACADEMICO_TEOLOGIA,ESTU_PRGM_ACADEMICO_TERAPIA CARDIORRESPIRATORIA,ESTU_PRGM_ACADEMICO_TERAPIA OCUPACIONAL,ESTU_PRGM_ACADEMICO_TERAPIA RESPIRATORIA,ESTU_PRGM_ACADEMICO_TERAPIAS PSICOSOCIALES,ESTU_PRGM_ACADEMICO_TRABAJO SOCIAL,ESTU_PRGM_ACADEMICO_TRADUCCION INGLES-FRANCES-ESPANOL,ESTU_PRGM_ACADEMICO_TURISMO,ESTU_PRGM_ACADEMICO_URBANISMO,ESTU_PRGM_ACADEMICO_ZOOTECNIA
0,547092,20195,3,4,0.0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,236193,20183,3,1,0.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,481044,20183,3,0,0.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,609421,20203,2,2,0.0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,89078,20183,2,4,0.0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
692495,783274,20195,7,0,6.0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
692496,310249,20183,7,4,6.0,1,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
692497,110623,20203,7,1,6.0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
692498,949271,20203,3,4,6.0,1,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
692499,44851,20203,4,2,6.0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
y = df.iloc[:, -1]
print(y.unique())
y

[0 1 3 2]

0         0
1         1
2         0
3         1
4         1
         ..
692495    3
692496    3
692497    2
692498    0
692499    0
Name: RENDIMIENTO_GLOBAL, Length: 692500, dtype: int64

In [21]:
## KEEPOUTPUT
from sklearn.ensemble import RandomForestClassifier

estimator = RandomForestClassifier(n_estimators=200, max_depth=20)
id_test,y_test,acuracy = split_fit_predict(estimator, X, y, train_pct=0.9)

Entrenando ...
Test ...
OK

In [22]:
acuracy

0.404

In [13]:
preds_ts = estimator.predict(Data_test[X.columns].drop(columns=['ID']))
preds_ts

array([1, 3, 0, ..., 3, 3, 3])

In [14]:
def map_numbers_to_strings(num):
    mapping = {
        0: 'bajo',
        1: 'medio-bajo',
        2: 'medio-alto',
        3: 'alto'
    }
    return mapping.get(num, 'desconocido')  # 'desconocido' es el valor por defecto si el número no está en el mapeo

# Aplicar la función a la columna}

Competition_kaggle = pd.DataFrame(preds_ts, columns=['RENDIMIENTO_GLOBAL'])


Competition_kaggle['RENDIMIENTO_GLOBAL'] = Competition_kaggle['RENDIMIENTO_GLOBAL'].apply(map_numbers_to_strings)

print("DataFrame con las categorías:")
print(Competition_kaggle)

DataFrame con las categorías:
       RENDIMIENTO_GLOBAL
0              medio-bajo
1                    alto
2                    bajo
3                    bajo
4                    bajo
...                   ...
296781         medio-alto
296782               alto
296783               alto
296784               alto
296785               alto

[296786 rows x 1 columns]

In [15]:
Competition_kaggle['RENDIMIENTO_GLOBAL'].unique()

array(['medio-bajo', 'alto', 'bajo', 'medio-alto'], dtype=object)

In [16]:
Competition_kaggle = pd.concat([Data_test['ID'],Competition_kaggle], axis=1)

In [17]:
Competition_kaggle

            ID RENDIMIENTO_GLOBAL
0       721274         medio-bajo
1       250531               alto
2       585681               bajo
3       767608               bajo
4       112077               bajo
...        ...                ...
296781  770258         medio-alto
296782  261058               alto
296783  390818               alto
296784  573310               alto
296785  812332               alto

[296786 rows x 2 columns]

In [18]:
# Guardar el DataFrame en un archivo CSV
Competition_kaggle.to_csv('Competition_kaggle.csv', index=False)